version: "3.8"
services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:10
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - flask-app-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - postgres
    environment:
      - TZ=Asia/Taipei
    entrypoint:
      [
        "flask",
        "--app",
        "web",
        "run",
        "--host",
        "0.0.0.0",
        "--debug"
      ]

volumes:
  flask-app-db:
    name: flask-app-db
